source 'https://www.rubygems.org' do
  gem 'appium_lib'
  gem 'appium_console'
  gem 'aws-sdk'
  gem 'rest-client'
  gem 'rspec'
  gem 'cucumber'
  gem 'rspec-expectations'
  gem 'spec'
  gem 'pry'
  gem 'pry-doc'
  gem 'pry-nav'
  gem 'watir-webdriver'
  gem 'watir-scroll'
  gem 'taza'
  gem 'test-helpers'
  gem 'activerecord'
  gem 'activesupport'
  gem 'activemodel'
  gem 'activerecord-jdbc-adapter'
  gem 'vinbot'
  gem 'report_builder'
  gem 'httparty'
  gem 'savon'
end